services:
  clubit-front:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clubit_front
    ports:
      - '4200:4200'
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - clubit_network

networks:
  clubit_network:
    external: true
